[build]
command = "npm ci || npm install && npm run build"
publish = "dist"

[build.environment]
# Stick to LTS to avoid oddities with native/optional deps
NODE_VERSION = "20"
# Make sure optional deps (like Parcel's rust binary) are NOT skipped
NPM_CONFIG_OPTIONAL = "true"
